export LD_LIBRARY_PATH := "../rust"

# GCC does not use LD_LIBRARY_PATH instead it use LIBRARY_PATH at compile time
export LIBRARY_PATH := LD_LIBRARY_PATH

lib:
    gcc -shared -lrustffihello -Wl,-rpath,$LD_LIBRARY_PATH -o libcffihello.so c.c

run:
    gcc -o run -lrustffihello c.c
    ./run
    rm run
