export LD_LIBRARY_PATH := "../c"

# GCC does not use LD_LIBRARY_PATH instead it use LIBRARY_PATH at compile time
export LIBRARY_PATH := LD_LIBRARY_PATH

lib:
    g++ -shared -lcffihello -o libc++ffihello.so c++.cpp

run:
    g++ -o run -lcffihello -Wl,--copy-dt-needed-entries c++.cpp
    ./run
    rm run
